### DISCUSSION TITLE
Project Launch

### DISCUSSION THREAD

**Discussion by rssXX** [luyadev/luya#2197] [Questions & Problems] [answered]
Hi! 

I have a ready-made project, but I can't get it started, please help me.

I'm stuck on the 'Installing the project' item, I don't understand how I can stuff "luya_composer" into the project. If everything is done up to this point, then I will get an error on localhost that I could not connect to the database, if I try to log into the database through the container, I will write an error that the password is not correct, but I can connect to the database from outside, but strangely enough with another password, which I did not specify yet in '.env', the docker ports and the ports on which I have mysql are different.

In README.md The project is specified:

```
# Sitis Luya default project


### Installation

use `composer install`

copy files:
```
configs.dist/env.php -> configs/env.php
configs.dist/env-local-db.php -> configs/env-local-db.php
```

setup database `configs/env-local-db.php`

```
./vendor/bin/luya migrate
./vendor/bin/luya import
./vendor/bin/luya admin/setup
```

## Docker

## Changing the database settings in the docker-compose files.yml and in the docker folder - env-local-db.php

Copying or renaming the config
```
cp .env.dist .env
cp docker/env* configs/
```

Creating containers

```
docker-compose build
docker-compose up -d
docker-compose ps
```

Installing the project

```
docker-compose run luya_composer install
docker-compose exec luya_php luya  migrate --migrationPath="@yii/rbac/migrations"
docker-compose exec luya_php luya  migrate
docker-compose exec luya_php luya  import
docker-compose exec luya_php luya  admin/setup
```

Follow the link

```
http://localhost:8080
http://localhost:8080/admin
```

To access the container
```
docker ps
# Example
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                              NAMES
793bdc1982ac        luyadefault_luya_php                                  "docker-php-entrypoi…"   18 minutes ago      Up 17 minutes       9000/tcp                           luyadefault_luya_php_1

docker exec -it <your_docker_container_id>  bash
```

## Styleguide
Link for styleguide
```
/styleguide
```
Password
```
555
```

```

docker-compose.yaml:

```
version: '3.7'

services:
  php:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    container_name: sitis_crm_core_php
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    networks:
      - sitis_crm_php_network
    depends_on:
      - db
  db:
    image: mariadb:10.3
    restart: unless-stopped
    container_name: sitis_crm_core_bd
    volumes:
      - sitis_crm_db-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${DB_PUBLIC_PORT}:3306
    networks:
      - sitis_crm_php_network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  nginx:
    build:
      context: ./docker/nginx
    restart: unless-stopped
    container_name: sitis_crm_core_nginx
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${WEB_SERVER_PUBLIC_PORT}:80
    depends_on:
      - php
    networks:
      - sitis_crm_php_network

volumes:
  sitis_crm_db-data:
    name: sitis_crm_db

networks:
  sitis_crm_php_network:
    name: sitis_crm_php_network
    driver: bridge
```
composer.json:

```
"config": {
    "allow-plugins": {
      "yiisoft/yii2-composer": true,
      "luyadev/luya-composer": true,
      "php-http/discovery": true
    }
  }
```
